package com.kit.wmsbackend.enums;

public enum PermissionCode {
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_ROLE_UPDATE,
    USER_WAREHOUSE_UPDATE,
    USER_DELETE,
    USER_RESTORE,
    USER_PROFILE_UPDATE,

    ROLE_READ,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,

    PERMISSION_READ,
    PERMISSION_CREATE,
    PERMISSION_UPDATE,
    PERMISSION_DELETE,

    PERMISSION_GROUP_READ,
    PERMISSION_GROUP_CREATE,
    PERMISSION_GROUP_UPDATE,
    PERMISSION_GROUP_DELETE,

    WAREHOUSE_READ,
    WAREHOUSE_CREATE,
    WAREHOUSE_UPDATE,
    WAREHOUSE_DELETE,
    WAREHOUSE_RESTORE,

    USER_WAREHOUSE_READ,
    USER_WAREHOUSE_ASSIGN,
    USER_WAREHOUSE_UNASSIGN,

    PRODUCT_CREATE,
    PRODUCT_READ,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
    PRODUCT_RESTORE,

    ATTRIBUTE_CREATE,
    ATTRIBUTE_READ,
    ATTRIBUTE_UPDATE,
    ATTRIBUTE_DELETE,

    ATTRIBUTE_VALUE_CREATE,
    ATTRIBUTE_VALUE_READ,
    ATTRIBUTE_VALUE_UPDATE,
    ATTRIBUTE_VALUE_DELETE,

    STOCK_TRANSACTION_CREATE,
    STOCK_TRANSACTION_READ,
    STOCK_TRANSACTION_UPDATE,
    STOCK_TRANSACTION_DELETE,

    INVENTORY_READ,
}
