spring:
  application:
    name: wms-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  mail:
    name: ${MAIL_NAME:WMS}
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                    enable: true
                    required: true
app:
  api:
    prefix: ${API_PREFIX:/api}
  server:
    url: ${SERVER_URL:http://localhost:8080}
  security:
    jwt:
      secret: ${JWT_SECRET:change-this-secret-key-to-at-least-32-characters}
      expiration: ${JWT_EXPIRATION:900000} # 15 minutes
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
      reset-expiration: ${JWT_RESET_EXPIRATION:600000} # 10 minutes
      onboarding-reset-expiration: ${JWT_ONBOARDING_RESET_EXPIRATION:86400000} # 1 day
  client:
    url: ${CLIENT_URL:http://localhost:3000}
  sequences:
    stock-transaction-seq-name: ${SEQUENCE_STOCK_TRANSACTION:stock_transaction_seq}
    import-prefix: ${SEQUENCE_IMPORT_PREFIX:IMP}
    export-prefix: ${SEQUENCE_EXPORT_PREFIX:EXP}
    adjustment-prefix: ${SEQUENCE_ADJUSTMENT_PREFIX:ADJ}
    user-seq-name: ${SEQUENCE_USER:user_seq}
    user-prefix: ${SEQUENCE_USER_PREFIX:USR}
    padding-length: ${SEQUENCE_PADDING_LENGTH:6}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO