package com.kit.wmsbackend.security;

public enum PermissionCode {
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    ROLE_READ,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,

    PERMISSION_READ,
    PERMISSION_CREATE,
    PERMISSION_UPDATE,
    PERMISSION_DELETE,

    PERMISSION_GROUP_READ,
    PERMISSION_GROUP_CREATE,
    PERMISSION_GROUP_UPDATE,
    PERMISSION_GROUP_DELETE,

    WAREHOUSE_READ,
    WAREHOUSE_CREATE,
    WAREHOUSE_UPDATE,
    WAREHOUSE_DELETE,

    USER_WAREHOUSE_READ,
    USER_WAREHOUSE_ASSIGN,
    USER_WAREHOUSE_UNASSIGN
}
