ALTER TABLE refresh_tokens
    ALTER COLUMN expires_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING expires_at::TIMESTAMP WITHOUT TIME ZONE,
    ALTER COLUMN last_used_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING last_used_at::TIMESTAMP WITHOUT TIME ZONE;
